[package]
name = "bkg-api"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
axum.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
bkg-core = { path = "../bkg-core" }
prometheus.workspace = true
uuid.workspace = true
plugin-cave = { path = "../../plugins/plugin-cave" }
plugin-p2p = { path = "../../plugins/plugin-p2p" }
